### ISSUE TITLE
Add ability to add a resource under an Environment - Kubernetes / Virtual Machine

### ISSUE THREAD

**Issue by Phil1972** [pulumi/pulumi-azuredevops#105]
Hi,

I am not able to find the functionality (maybe I have it wrong), but is there a way to create a resource under an environment? ie: either add a kubernetes namespace or a virtual machine.

We are presently stuck at creating a functioning environment because this is missing (or we are not able to find out how to do it).

The missing piece is supposed to under-the-hood call MS azure devops REST API:
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/kubernetes/add?view=azure-devops-rest-6.0

POST [https://dev.azure.com/{organization}/{project}/_apis/distributedtask/environments/{environmentId}/providers/kubernetes?api-version=6.0-preview.1](https://dev.azure.com/%7Borganization%7D/%7Bproject%7D/_apis/distributedtask/environments/%7BenvironmentId%7D/providers/kubernetes?api-version=6.0-preview.1)

Thanks for your time,

**Comment by guineveresaenger** [comment]
Hi @Phil1972 - I don't have fully enough context to be able to help you with provider specifics, but you should be able to leverage [pulumi.Parent](https://www.pulumi.com/docs/intro/concepts/resources/options/parent/) to make resources depend on each other.

You may find folks with similar situations to yours in our [community slack](https://slack.pulumi.com/)

**Comment by Phil1972** [comment]
Anyone has news about this requested feature ?

Thanks,

**Comment by jkodroff** [comment]
@Phil1972 As you've figured out, this is an upstream bug: https://github.com/microsoft/terraform-provider-azuredevops/issues/584

Which in turn cannot be fixed because of: https://github.com/microsoft/azure-devops-go-api/issues/116

There's not much we can do but wait for the upstream bugs to be fixed. I'm sure that's disappointing to hear - I wish it was something we could fix.

When the upstream issues are resolved, we'll update the provider and the issue should be fixed for you.
